%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

%global __cmake_in_source_build 1

Name:           ros-jazzy-control-toolbox
Version:        4.8.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS control_toolbox package

License:        Apache License 2.0
URL:            https://control.ros.org
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       fmt-devel
Requires:       ros-jazzy-backward-ros
Requires:       ros-jazzy-control-msgs
Requires:       ros-jazzy-filters
Requires:       ros-jazzy-generate-parameter-library
Requires:       ros-jazzy-geometry-msgs
Requires:       ros-jazzy-pluginlib
Requires:       ros-jazzy-rclcpp
Requires:       ros-jazzy-rcutils
Requires:       ros-jazzy-realtime-tools
Requires:       ros-jazzy-tf2
Requires:       ros-jazzy-tf2-geometry-msgs
Requires:       ros-jazzy-tf2-ros
Requires:       ros-jazzy-ros-workspace
BuildRequires:  eigen3-devel
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-backward-ros
BuildRequires:  ros-jazzy-control-msgs
BuildRequires:  ros-jazzy-filters
BuildRequires:  ros-jazzy-generate-parameter-library
BuildRequires:  ros-jazzy-geometry-msgs
BuildRequires:  ros-jazzy-pluginlib
BuildRequires:  ros-jazzy-rclcpp
BuildRequires:  ros-jazzy-rcutils
BuildRequires:  ros-jazzy-realtime-tools
BuildRequires:  ros-jazzy-ros2-control-cmake
BuildRequires:  ros-jazzy-tf2
BuildRequires:  ros-jazzy-tf2-geometry-msgs
BuildRequires:  ros-jazzy-tf2-ros
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-jazzy-ament-cmake-gmock
BuildRequires:  ros-jazzy-rclcpp-lifecycle
%endif

%description
The control toolbox contains modules that are useful across all controllers.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Thu Oct 02 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 4.8.0-1
- Autogenerated by Bloom

* Mon Sep 22 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 4.7.1-1
- Autogenerated by Bloom

* Wed Aug 13 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 4.7.0-1
- Autogenerated by Bloom

* Tue Jul 22 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 4.6.0-1
- Autogenerated by Bloom

* Wed Jun 18 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 4.5.0-1
- Autogenerated by Bloom

* Fri May 23 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 4.4.0-1
- Autogenerated by Bloom

* Thu Apr 24 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 4.3.0-1
- Autogenerated by Bloom

* Sat Apr 19 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 4.2.0-1
- Autogenerated by Bloom

* Sun Apr 06 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 4.1.0-1
- Autogenerated by Bloom

* Thu Feb 13 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 4.0.1-1
- Autogenerated by Bloom

* Wed Jan 29 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 4.0.0-1
- Autogenerated by Bloom

* Wed Jan 15 2025 Bence Magyar <bence.magyar.robotics@gmail.com> - 3.5.0-1
- Autogenerated by Bloom

* Sun Dec 08 2024 Bence Magyar <bence.magyar.robotics@gmail.com> - 3.4.0-1
- Autogenerated by Bloom

* Mon Oct 28 2024 Bence Magyar <bence.magyar.robotics@gmail.com> - 3.3.0-1
- Autogenerated by Bloom

* Thu Apr 18 2024 Bence Magyar <bence.magyar.robotics@gmail.com> - 3.2.0-3
- Autogenerated by Bloom

* Tue Mar 05 2024 Bence Magyar <bence.magyar.robotics@gmail.com> - 3.2.0-2
- Autogenerated by Bloom

