Name:           ros-lunar-control-toolbox
Version:        1.16.0
Release:        0%{?dist}
Summary:        ROS control_toolbox package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/control_toolbox
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-lunar-cmake-modules
Requires:       ros-lunar-control-msgs
Requires:       ros-lunar-dynamic-reconfigure
Requires:       ros-lunar-message-runtime
Requires:       ros-lunar-realtime-tools
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-std-msgs
Requires:       tinyxml-devel
BuildRequires:  ros-lunar-catkin >= 0.5.68
BuildRequires:  ros-lunar-cmake-modules
BuildRequires:  ros-lunar-control-msgs
BuildRequires:  ros-lunar-dynamic-reconfigure
BuildRequires:  ros-lunar-message-generation
BuildRequires:  ros-lunar-realtime-tools
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-std-msgs
BuildRequires:  tinyxml-devel

%description
The control toolbox contains modules that are useful across all controllers.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Thu Nov 30 2017 Sachin Chitta <sachinc@willowgarage.com> - 1.16.0-0
- Autogenerated by Bloom

* Tue Mar 21 2017 Sachin Chitta <sachinc@willowgarage.com> - 1.15.0-0
- Autogenerated by Bloom

