Name:           ros-jade-control-toolbox
Version:        1.13.1
Release:        0%{?dist}
Summary:        ROS control_toolbox package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/control_toolbox
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-cmake-modules
Requires:       ros-jade-dynamic-reconfigure
Requires:       ros-jade-message-runtime
Requires:       ros-jade-realtime-tools
Requires:       ros-jade-roscpp
Requires:       ros-jade-std-msgs
Requires:       tinyxml-devel
BuildRequires:  ros-jade-catkin >= 0.5.68
BuildRequires:  ros-jade-cmake-modules
BuildRequires:  ros-jade-dynamic-reconfigure
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-realtime-tools
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-std-msgs
BuildRequires:  tinyxml-devel

%description
The control toolbox contains modules that are useful across all controllers.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Thu Apr 30 2015 Sachin Chitta <sachinc@willowgarage.com> - 1.13.1-0
- Autogenerated by Bloom

